version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-csharp
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  mongodb:

    image: mongo:6.0
    container_name: mongodb-csharp
    ports:
      - "27017:27017" 
    volumes:
      - mongodb_data:/data/db

  mailhog:
     image: mailhog/mailhog
     container_name: mailhog-csharp
     ports:
        - "1025:1025" 
        - "8025:8025" 

volumes:
  mongodb_data:


